version: "3"

services:
  db:
    image: mysql:5.7
    container_name: "lara-db"
    restart: "always"
    ports:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "apple"
      MYSQL_DATABASE: "laravel-crud"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
